# Generated by Django 5.2 on 2025-04-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adminstration',
            new_name='Restaurant',
        ),
    ]
