# Generated by Django 5.2 on 2025-05-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_order_orderitem_table_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/projectapp/menu_images/'),
        ),
    ]
