# Generated by Django 5.2 on 2025-05-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_restaurant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projectapp/menu_images/'),
        ),
    ]
