# Generated by Django 5.2 on 2025-05-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_alter_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='restaurant',
        ),
    ]
