# Generated by Django 5.2 on 2025-05-09 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_remove_userprofile_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='projectapp.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
