# Generated by Django 5.2 on 2025-05-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_foodcategory_restaurant_alter_foodcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='qr_code_url',
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='table_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
