# Generated by Django 5.2 on 2025-05-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0012_remove_table_qr_code_url_table_name_table_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('restaurant', 'table_id')},
        ),
    ]
