services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=myproject_db
      - MYSQL_ROOT_PASSWORD=30af44cc6a537e024290829f
    volumes:
      - db_data:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10

  web:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PORT=8080
    volumes:
      - media:/app/media

volumes:
  db_data:
  media:

